### ISSUE TITLE
error on importing Token

### ISSUE THREAD

**Issue by herlimenezes** [allenai/allennlp#581]
As I try to use jupyter notebook in a Python3.6 virtual environment  these lines issued an error:
*********************************************************************************
from allennlp.data import Token
from allennlp.data.fields import TextField, LabelField
from allennlp.data.token_indexers import SingleIdTokenIndexer
*********************************************************************************
I got this error:

ImportError                               Traceback (most recent call last)
<ipython-input-7-755d3200beb4> in <module>()
----> 1 from allennlp.data import Token
      2 from allennlp.data.fields import TextField, LabelField
      3 from allennlp.data.token_indexers import SingleIdTokenIndexer

ImportError: cannot import name 'Token'
I am running a Linux distro Fedora 25, on an AMD Phenon 6 processor, with no GPU.

**Comment by DeNeutoy** [comment]
Hello! This is happening because you have an old version of the allennlp pip package. Please run `pip install allennlp --ignore-installed`.

**Comment by herlimenezes** [comment]
Hello! I cloned the repository and installed in a Python 3.6 virtual environment. Installation was successful, however the same issue persists:
My pyvenv.cfg is:
**********************************************
home = /usr/bin
include-system-site-packages = true
version = 3.6.2
*********************************************
got  the same error:
*************************************************
ImportError                               Traceback (most recent call last)
<ipython-input-2-d3f364913317> in <module>()
----> 1 from allennlp.data import Token
      2 from allennlp.data.fields import TextField, LabelField
      3 from allennlp.data.token_indexers import SingleIdTokenIndexer
      4 
      5 review = TextField(list(map(Token, ["This", "movie", "was", "awful", "!"])), token_indexers={"tokens": SingleIdTokenIndexer()})

ImportError: cannot import name 'Token'
***************************************************************

**Comment by DeNeutoy** [comment]
I'm 99% sure this is the reason - please check that your jupyter notebook is running the python binary from your virtual environment. Additionally, you seem to have included system site packages in your virtual environment, which is bad practice and likely the cause of the issue if you have previously installed allennlp via pip. We have instructions for creating a conda environment in our Readme.

**Comment by herlimenezes** [comment]
Ok, Mark, I will check all instalation steps, and if needed, I will
reinstall it from the scratch. I think allennlp would be nice to perform
some experiments in my doctoral research. I have been using
practicNLPtools, an old Python package, which is a wrap of SENNA. I think
allennlp would be nice.

Thank you once more.

Herli Menezes

*Amor, trabalho e conhecimento são as fontes da nossa vida. Deveriam,
também, governá-la.*

*(Wilhelm Reich)*


2017-12-06 19:01 GMT-02:00 Mark Neumann <notifications@github.com>:

**Comment by herlimenezes** [comment]
Hello, Mark,

As I told you in the last message, I did a fresh install following the
steps recomended. As I executed pytest -v I got no errors but a criptic
message "llegal instruction (core dumped)" (legal or illegal?)


<goog_1227269206>
https://paste.fedoraproject.org/paste/b7JUEpjXu34wbC6jUFokWw/

I executed the tutorial by jupyter notebook and there was no more errors
related to Token and I found that a possible source of that error was that
pytorch was missing in virtual environment, although it was installed in my
machine.

Thank you very much!


Herli Menezes

*Amor, trabalho e conhecimento são as fontes da nossa vida. Deveriam,
também, governá-la.*

*(Wilhelm Reich)*


2017-12-06 19:14 GMT-02:00 Herli Joaquim de Menezes <herlimenezes@gmail.com>
:

**Comment by DeNeutoy** [comment]
Yes you need to have Pytorch in your virtual environment. Please see step 5 here: 
https://github.com/allenai/allennlp#setting-up-a-conda-development-environment.

**Comment by herlimenezes** [comment]
Thank you Mark.
I have already installed PyTorch and the Token issue was solved. However i
went into some troubles with Jupyter which is unstable and dies silently,
but I have not examined what caused it. I guess that is sometrhing with
ipython, but I am not sure.

Thanks for your precious hints.

Herli Menezes

*Amor, trabalho e conhecimento são as fontes da nossa vida. Deveriam,
também, governá-la.*

*(Wilhelm Reich)*


2017-12-07 18:12 GMT-02:00 Mark Neumann <notifications@github.com>:

**Comment by herlimenezes** [comment]
Hello, Mark. 
I have revised allennlp instalation and ran pytest -v. Test failed with an Illegal instruction (core dumped), I cannot understand why, A I tried to run jupyter notebook data pipeline, jypiter dies silently, are these issues related?

Thank you.

**Comment by DeNeutoy** [comment]
I would recommend re-installing Ipython and Jupyter, but apart from that i'm not sure how much I can really help, sorry!

**Comment by BobbleHeadAlien** [comment]
Hi, I am facing the same error when importing Batch, PLease help

**Comment by matt-gardner** [comment]
`Batch` only exists in the newest, unreleased version of allennlp.  If you've installed from pip and you're following tutorials, be sure you're on the 0.3.0 tag when looking, as the tutorials on master reflect the code on master, not version 0.3.0.

If you've cloned from master or installed the current master using pip, and you're still running into this issue, let us know.
