### ISSUE TITLE
OpenIE demo not working with 1.0.0rc5

### ISSUE THREAD

**Issue by FelixLabelle** [allenai/allennlp#4325]
## Description

I'm trying to run the [OpenIE demo](https://demo.allennlp.org/open-information-extraction) with a more recent release (1.0.0rc5 instead of 1.0.0rc3). There appears to have been a change in the layout of the AllenNLP modules (syntax no longer exists).

Originally I got an error to that effect and checked the layout of the files. I replaced "import allennlp_models.syntax.srl" with "allennlp_models.structured_prediction.predictors.srl", but now get the second error listed below. I'm not familiar with the design of this API, so I figured I would ask what the correct import before going further.

<details>
<summary><b>Original traceback:</b></summary>
<p>
Traceback (most recent call last):
  File "qa_models.py", line 4, in <module>
    import allennlp_models.syntax.srl
ModuleNotFoundError: No module named 'allennlp_models.syntax'

</p>
</details>

<details>
<summary><b>Latest traceback:</b></summary>
<p>
Traceback (most recent call last):
  File "qa_models.py", line 41, in <module>
    main(args)
  File "qa_models.py", line 31, in main
    prediction = predictor.prediction(register[-5])
AttributeError: 'SemanticRoleLabelerPredictor' object has no attribute 'prediction'
</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Ubuntu 18.04

Python version: Python 3.7.3

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

Using allennlp 1.0.0rc5 run the demo code.

</p>
</details>
